# Generated by Django 4.2.2 on 2023-06-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
