# Generated by Django 4.2.2 on 2023-07-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="social",
            name="email",
            field=models.CharField(default="dsd", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="social",
            name="phone",
            field=models.CharField(default="dsd", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tracking",
            name="tracking_number",
            field=models.TextField(null=True),
        ),
    ]
