# Generated by Django 4.2 on 2023-05-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_category',
            name='slug',
        ),
    ]
