# Generated by Django 4.2 on 2023-06-01 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_remove_main_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimageurl',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecom.product'),
        ),
    ]
