# Generated by Django 4.2 on 2023-06-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_productsimageurl_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='banner',
            field=models.FileField(blank=True, upload_to='sub_category'),
        ),
    ]
