# Generated by Django 4.2.2 on 2023-06-15 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0004_alter_product_stock_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_stock",
            name="Color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecom.color",
            ),
        ),
        migrations.AlterField(
            model_name="product_stock",
            name="Size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecom.size",
            ),
        ),
    ]
