# Generated by Django 4.2 on 2023-06-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='icon',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
