# Generated by Django 4.2.2 on 2023-06-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0005_alter_product_stock_color_alter_product_stock_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracking",
            name="link",
        ),
        migrations.RemoveField(
            model_name="tracking",
            name="tracking_status",
        ),
        migrations.AddField(
            model_name="tracking",
            name="data",
            field=models.TextField(null=True),
        ),
    ]
