# Generated by Django 4.2.2 on 2023-06-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0006_remove_tracking_link_remove_tracking_tracking_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="Num",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
