# Generated by Django 4.0.3 on 2023-06-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_product_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model_Name',
            new_name='name',
        ),
    ]
