# Generated by Django 4.0.3 on 2023-06-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_rename_model_name_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured_image',
            new_name='image',
        ),
    ]
