# Generated by Django 4.2.2 on 2023-07-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0008_product_seller_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="mobile_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="zip",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
