# Generated by Django 4.0.3 on 2023-06-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_rename_featured_image_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimageurl',
            name='Image_url',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
