# Generated by Django 4.0.3 on 2023-06-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_remove_order_items_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
    ]
