# Generated by Django 4.0.3 on 2023-06-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0019_order_invalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
