# Generated by Django 4.0.3 on 2023-06-06 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_coupons', '0002_alter_allowedusersrule_id_alter_coupon_code_and_more'),
        ('ecom', '0026_checkout_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='coupons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_simple_coupons.coupon'),
        ),
    ]
