# Generated by Django 4.0.3 on 2023-06-08 07:14

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0030_alter_mail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=16, max_length=40, prefix='GIF=', primary_key=True, serialize=False),
        ),
    ]
