# Generated by Django 4.0.3 on 2023-06-08 16:01

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0031_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=16, max_length=40, prefix='gif-', primary_key=True, serialize=False),
        ),
    ]
